const Strings = {
  welcome: 'Welcome on board!',
  lets: 'Lets help you meet up your tasks',
  name: 'Enter your name',
  email: 'Enter your email',
  password: 'Enter password',
  cpassword: 'Confirm password',
  username: 'Enter your username',
  register: 'Register',
  login: 'Login',
  already: 'Already have an account?',
  dont: 'Dont have an account?',
  signIn: 'Sign in',
  signUp: 'Sign up',
  please: 'Please sign in to continue',
  title: 'Title',
  description: 'Description',
  assignee: 'Assignee',
  create: 'Create a new task',
  save_task: 'Save Task',
  new_task: 'New Task',
  update_task: 'Update Task',
};

export default Strings;
